name: Locust Load Test

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch: # Manual trigger

jobs:
  locust-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Python Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install locust

      - name: Run Locust Load Test
        run: locust -f load_test.py --headless -u 100 -r 10 --host=https://staging.example.com