version: '3.8'

services:
  inventory-service:
    image: inventory-service:latest
    container_name: inventory-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DATABASE_URL=jdbc:postgresql://db:5432/inventory
      - DATABASE_USERNAME=your_db_username
      - DATABASE_PASSWORD=your_db_password
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: inventory-db
    environment:
      - POSTGRES_DB=inventory
      - POSTGRES_USER=your_db_username
      - POSTGRES_PASSWORD=your_db_password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:services:
